version: '3.8'

services:
  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${USER_DB_LOCAL_PORT}:${USER_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

  auth-db:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_DB_LOCAL_PORT}:${AUTH_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - bank-network


  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_PORT}"
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user-service-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: user-db
      DB_PORT: ${USER_DB_PORT}
      DB_NAME: ${USER_DB_NAME}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bank-network

  auth-service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    container_name: auth-service-app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_SURNAME: ${ADMIN_SURNAME}
      DB_HOST: auth-db
      DB_PORT: ${AUTH_DB_PORT}
      DB_NAME: ${AUTH_DB_NAME}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - bank-network



volumes:
  user_db_data:
  auth_db_data:

networks:
  bank-network:
    driver: bridge