version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CONTAINER_PORT}
    ports:
      - "${ZOOKEEPER_HOST_PORT}:${ZOOKEEPER_CONTAINER_PORT}"
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo ruok | nc localhost ${ZOOKEEPER_CONTAINER_PORT} | grep imok || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CONTAINER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_CONTAINER_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    ports:
      - "${KAFKA_HOST_PORT}:${KAFKA_CONTAINER_PORT}"
    healthcheck:
      test: [ "CMD", "bash", "-c", "kafka-broker-api-versions --bootstrap-server localhost:${KAFKA_CONTAINER_PORT} || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bank-network

  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${USER_DB_LOCAL_PORT}:${USER_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - bank-network

  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${ORDER_DB_LOCAL_PORT}:${ORDER_DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - bank-network


  auth-db:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_DB_LOCAL_PORT}:${AUTH_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - bank-network


  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_PORT}"
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway-app
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
    depends_on:
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - bank-network

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user-service-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: user-db
      DB_PORT: ${USER_DB_PORT}
      DB_NAME: ${USER_DB_NAME}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      KAFKA_BOOTSTRAP_SERVERS: kafka:${KAFKA_CONTAINER_PORT}
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - bank-network

  auth-service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    container_name: auth-service-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_SURNAME: ${ADMIN_SURNAME}
      DB_HOST: auth-db
      DB_PORT: ${AUTH_DB_PORT}
      DB_NAME: ${AUTH_DB_NAME}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      KAFKA_BOOTSTRAP_SERVERS: kafka:${KAFKA_CONTAINER_PORT}
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN}
    depends_on:
      auth-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - bank-network

  order-service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: order-service-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ORDER_DB_HOST: order-db
      ORDER_DB_PORT: ${ORDER_DB_PORT}
      ORDER_DB_NAME: ${ORDER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    depends_on:
      order-db:
        condition: service_healthy
      user-service:
        condition: service_started
      auth-service:
        condition: service_started
    networks:
      - bank-network

volumes:
  user_db_data:
  auth_db_data:
  order_db_data:

networks:
  bank-network:
    driver: bridge