server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
---

spring:
  application:
    name: user_service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

  data:
    redis:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
          time-between-eviction-runs: 60s

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
---
spring:
  config:
    activate:
      on-profile: local


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bank_innowise_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

internal:
  service:
    token: ${INTERNAL_SERVICE_TOKEN}